### ISSUE TITLE
make the pymol_temp directory unique

### ISSUE THREAD

**Issue by RudoRoemer** [erickmartins/pdb2movie#12]
When creating new movies, we generate a directory, e.g. Runs/2.0/Mode07-pos/pymol_temp. But this means that movie generation with different "--video pymol.py" settings share that same pymol_temp directory and hence two such jobs will overwrite each other. It would hence be good if each directory pymol_temp would be **unique.**

**Comment by RudoRoemer** [comment]
This will happen a lot if, as I am doing at the moment, different views of the same protein movement are being generated.

**Comment by james-panayis** [comment]
This is solved by pull request #14 - the outputs are now unique based on all the input arguments.
